//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookAppointmentScheduler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan ScheduleStartTime {
            get {
                return ((global::System.TimeSpan)(this["ScheduleStartTime"]));
            }
            set {
                this["ScheduleStartTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int ScheduleIntervalInHours {
            get {
                return ((int)(this["ScheduleIntervalInHours"]));
            }
            set {
                this["ScheduleIntervalInHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>14:30:00</string>
  <string>15:00:00</string>
  <string>15:30:00</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BookingTimesToCheck {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BookingTimesToCheck"]));
            }
            set {
                this["BookingTimesToCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DurationOfBookingInMinutes {
            get {
                return ((int)(this["DurationOfBookingInMinutes"]));
            }
            set {
                this["DurationOfBookingInMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Saturday</string>\r\n  <string>Sunday</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BookingDayBlackList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BookingDayBlackList"]));
            }
            set {
                this["BookingDayBlackList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#AU MELY Room Table Tennis")]
        public string BookingLocation {
            get {
                return ((string)(this["BookingLocation"]));
            }
            set {
                this["BookingLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int BookingDaysInFuture {
            get {
                return ((int)(this["BookingDaysInFuture"]));
            }
            set {
                this["BookingDaysInFuture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Daniel Mastrowicz</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BookingRecipients {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BookingRecipients"]));
            }
            set {
                this["BookingRecipients"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TT booking.")]
        public string BookingBodyText {
            get {
                return ((string)(this["BookingBodyText"]));
            }
            set {
                this["BookingBodyText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TT")]
        public string BookingSubjectText {
            get {
                return ((string)(this["BookingSubjectText"]));
            }
            set {
                this["BookingSubjectText"] = value;
            }
        }
    }
}
